// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svwmsucxcfzzkxncnvac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2d21zdWN4Y2Z6emt4bmNudmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MjM3ODIsImV4cCI6MjA1MzE5OTc4Mn0.dbUpHrrotLkjSahm6V7kfsTeX3JaaZtlgvm5ODPcsVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);